services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: ci
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: test
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/1

  postgres:
    image: ghcr.io/dualboot-partners/db90-rails/timescaledb:latest-pg17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: ghcr.io/dualboot-partners/db90-rails/redis:7.2
