FROM quay.io/keycloak/keycloak:26.6.4 AS builder

ENV KC_HEALTH_ENABLED=true
ENV KC_DB=postgres

COPY keycloak/realm-import.json /opt/keycloak/data/import/realm-import.json
COPY keycloak/themes /opt/keycloak/themes

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.6.4

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
