require "temporalio/activity"
require "json"
require "digest"

module Activities
  class SanitizationActivity < Temporalio::Activity::Definition
    REDACTION_PLACEHOLDER = "[REDACTED]"
    MASK_CHAR = "*"

    # Structural identifiers generated by connectors for dedup/correlation, not
    # user-authored content. Excluded by key name so secret patterns (which must
    # stay broad enough to catch UUIDs/SHAs pasted into prompt/assistant text —
    # see claude_chat_sanitization_spec.rb AC 8) don't corrupt session tracking
    # (e.g. Cursor's "<uuid>:<turnIndex>" session_id).
    NON_CONTENT_KEYS = %w[session_id cursor_session_id generation_id].freeze

    def execute(params)
      Temporalio::Activity::Context.current.heartbeat("Sanitizing event content")

      raw_payload = params["raw_payload"]
      policy = params["policy"]
      classification = params["classification"]

      return { "sanitized_payload" => raw_payload, "changes" => [] } unless classification["requires_sanitization"]

      changes = []
      excluded_keys = policy.fetch("excluded_keys", []).map { |k| k.to_s.downcase }

      # Parse JSON strings so excluded_keys are respected at the field level.
      # Without this, the regex runs against the raw JSON string and matches
      # structural values (commit hashes, branch names, workspace folder IDs).
      parsed_payload, was_json_string = parse_payload(raw_payload)
      sanitized = deep_copy(parsed_payload)

      policy["rules"].each do |category, config|
        next unless config["enabled"]

        config["patterns"].each do |pattern_name, pattern|
          Temporalio::Activity::Context.current.heartbeat("Sanitizing #{category}/#{pattern_name}")

          regex = Regexp.new(pattern, Regexp::IGNORECASE)
          action = config["action"]

          sanitized, pattern_changes = apply_sanitization(sanitized, regex, action, category, pattern_name, excluded_keys)
          changes.concat(pattern_changes)
        end
      end

      sanitized_output = was_json_string ? JSON.generate(sanitized) : sanitized

      {
        "sanitized_payload" => sanitized_output,
        "changes" => changes,
        "change_count" => changes.length,
        "original_size" => calculate_size(raw_payload),
        "sanitized_size" => calculate_size(sanitized_output)
      }
    end

    private

    # Returns [parsed_structure, reserialize_to_json_string?]. Falls back to
    # treating the payload as an opaque string when it isn't valid JSON, so
    # non-JSON raw_payloads still get flat-string scanning as before.
    def parse_payload(raw_payload)
      return [raw_payload, false] unless raw_payload.is_a?(String)

      [JSON.parse(raw_payload), true]
    rescue JSON::ParserError
      [raw_payload, false]
    end

    def deep_copy(obj)
      case obj
      when Hash
        obj.transform_values { |v| deep_copy(v) }
      when Array
        obj.map { |v| deep_copy(v) }
      when String
        obj.dup
      else
        obj
      end
    end

    def apply_sanitization(data, regex, action, category, pattern_name, excluded_keys = [])
      changes = []

      case data
      when Hash
        sanitized = {}
        data.each do |key, value|
          if NON_CONTENT_KEYS.include?(key) || excluded_keys.include?(key.to_s.downcase)
            sanitized[key] = value
            next
          end

          sanitized_value, value_changes = apply_sanitization(value, regex, action, category, pattern_name, excluded_keys)
          sanitized[key] = sanitized_value
          changes.concat(value_changes.map { |c| c.merge("path" => "#{key}.#{c['path']}".sub(/\.$/, "")) })
        end
        [sanitized, changes]
      when Array
        sanitized = []
        data.each_with_index do |value, idx|
          sanitized_value, value_changes = apply_sanitization(value, regex, action, category, pattern_name, excluded_keys)
          sanitized << sanitized_value
          changes.concat(value_changes.map { |c| c.merge("path" => "[#{idx}].#{c['path']}".sub(/\.$/, "")) })
        end
        [sanitized, changes]
      when String
        sanitize_string(data, regex, action, category, pattern_name)
      else
        [data, []]
      end
    end

    def sanitize_string(str, regex, action, category, pattern_name)
      changes = []
      original = str.dup

      sanitized = str.gsub(regex) do |match|
        changes << {
          "category" => category,
          "pattern" => pattern_name,
          "action" => action,
          "original_length" => match.length,
          "path" => ""
        }

        case action
        when "redact"
          REDACTION_PLACEHOLDER
        when "mask"
          mask_value(match)
        when "hash"
          hash_value(match)
        when "truncate"
          truncate_value(match)
        else
          REDACTION_PLACEHOLDER
        end
      end

      [sanitized, changes]
    end

    def mask_value(value)
      return MASK_CHAR * 4 if value.length <= 4

      visible_start = [value.length / 4, 2].min
      visible_end = [value.length / 4, 2].min
      masked_length = value.length - visible_start - visible_end

      value[0, visible_start] + (MASK_CHAR * masked_length) + value[-visible_end, visible_end]
    end

    def hash_value(value)
      digest = Digest::SHA256.hexdigest(value)
      "[HASH:#{digest[0, 12]}]"
    end

    def truncate_value(value)
      return value if value.length <= 4

      "#{value[0, 2]}...#{value[-2, 2]}"
    end

    def calculate_size(data)
      case data
      when String
        data.bytesize
      else
        JSON.generate(data).bytesize
      end
    rescue
      0
    end
  end
end
