# frozen_string_literal: true

require "rails_helper"
require "rake"

RSpec.describe "db90:cleanup_claude_noise_events" do
  before(:all) do
    Rails.application.load_tasks
  end

  let(:task) { Rake::Task["db90:cleanup_claude_noise_events"] }
  let(:organization) { create(:organization) }

  before do
    task.reenable
    ENV["ALLOW_PRODUCTION_CLEANUP"] = "1"
  end

  after do
    ENV.delete("ALLOW_PRODUCTION_CLEANUP")
  end

  def claude_noise_event(prompt_text, **overrides)
    create(:tool_event,
      organization: organization,
      tool_name: "claude_code",
      model: nil,
      tokens_in: 0,
      tokens_out: 0,
      cost_usd: 0,
      metadata: { "transcript_source" => "claude_jsonl", "prompt_text" => prompt_text },
      **overrides
    )
  end

  def real_claude_event(**overrides)
    create(:tool_event,
      organization: organization,
      tool_name: "claude_code",
      model: "claude-sonnet-4-6",
      tokens_in: 150,
      tokens_out: 40,
      metadata: { "transcript_source" => "claude_jsonl", "prompt_text" => "How do I refactor this?" },
      **overrides
    )
  end

  describe "live run" do
    it "deletes local-command-caveat events" do
      noise = claude_noise_event("<local-command-caveat>Caveat: messages below were generated by local commands.</local-command-caveat>")
      real  = real_claude_event

      expect { task.invoke(organization.slug) }.to change(ToolEvent, :count).by(-1)
      expect(ToolEvent.exists?(noise.id)).to be false
      expect(ToolEvent.exists?(real.id)).to be true
    end

    it "deletes local-command-stdout events" do
      noise = claude_noise_event("<local-command-stdout>output here</local-command-stdout>")

      expect { task.invoke(organization.slug) }.to change(ToolEvent, :count).by(-1)
      expect(ToolEvent.exists?(noise.id)).to be false
    end

    it "deletes command-name events" do
      noise = claude_noise_event("<command-name>/exit</command-name>\n<command-message>exit</command-message>")

      expect { task.invoke(organization.slug) }.to change(ToolEvent, :count).by(-1)
      expect(ToolEvent.exists?(noise.id)).to be false
    end

    it "preserves noise-pattern events that have non-zero tokens" do
      kept = create(:tool_event,
        organization: organization,
        tool_name: "claude_code",
        model: nil,
        tokens_in: 50,
        tokens_out: 0,
        metadata: { "transcript_source" => "claude_jsonl", "prompt_text" => "<local-command-caveat>...</local-command-caveat>" }
      )

      expect { task.invoke(organization.slug) }.not_to change(ToolEvent, :count)
      expect(ToolEvent.exists?(kept.id)).to be true
    end

    it "preserves noise-pattern events that have a model" do
      kept = create(:tool_event,
        organization: organization,
        tool_name: "claude_code",
        model: "claude-sonnet-4-6",
        tokens_in: 0,
        tokens_out: 0,
        metadata: { "transcript_source" => "claude_jsonl", "prompt_text" => "<local-command-caveat>...</local-command-caveat>" }
      )

      expect { task.invoke(organization.slug) }.not_to change(ToolEvent, :count)
      expect(ToolEvent.exists?(kept.id)).to be true
    end

    it "only deletes events belonging to the specified organization" do
      other_org   = create(:organization)
      other_noise = claude_noise_event("<local-command-caveat>...</local-command-caveat>", organization: other_org)
      my_noise    = claude_noise_event("<local-command-caveat>...</local-command-caveat>")

      task.invoke(organization.slug)

      expect(ToolEvent.exists?(my_noise.id)).to be false
      expect(ToolEvent.exists?(other_noise.id)).to be true
    end

    it "does nothing when no noise events exist" do
      real_claude_event
      expect { task.invoke(organization.slug) }.not_to change(ToolEvent, :count)
    end
  end

  describe "dry-run mode" do
    it "does not delete any events" do
      claude_noise_event("<local-command-caveat>...</local-command-caveat>")

      expect { task.invoke(organization.slug, "dry_run") }.not_to change(ToolEvent, :count)
    end
  end

  describe "unknown organization" do
    it "aborts when the slug does not match any organization" do
      expect { task.invoke("nonexistent-org-slug") }.to raise_error(SystemExit)
    end

    it "aborts when no organization slug is provided" do
      expect { task.invoke }.to raise_error(SystemExit)
    end
  end
end
